# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import chat_pb2 as chat__pb2


class InternalChatStub(object):
    """InternalChat: 内网流式聊天服务（Stub 供客户端使用）"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
            "/finserve.internal.InternalChat/StreamChat",
            request_serializer=chat__pb2.StreamChatRequest.SerializeToString,
            response_deserializer=chat__pb2.StreamChatChunk.FromString,
        )


class InternalChatServicer(object):
    """InternalChat: 内网流式聊天服务（Servicer 基类，由服务端继承并实现）"""

    def StreamChat(self, request, context):
        """StreamChat: 服务端流式返回生成内容
        请求 StreamChatRequest，流式返回 StreamChatChunk。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InternalChatServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamChat": grpc.unary_stream_rpc_method_handler(
            servicer.StreamChat,
            request_deserializer=chat__pb2.StreamChatRequest.FromString,
            response_serializer=chat__pb2.StreamChatChunk.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "finserve.internal.InternalChat", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
