# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/chat.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'proto/chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10proto/chat.proto\x12\x11\x66inserve.internal\"_\n\x11StreamChatRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x11\n\texpert_id\x18\x02 \x01(\t\x12\x12\n\nmax_tokens\x18\x03 \x01(\x05\x12\x13\n\x0btemperature\x18\x04 \x01(\x02\"7\n\x0fStreamChatChunk\x12\x12\n\ntext_delta\x18\x01 \x01(\t\x12\x10\n\x08\x66inished\x18\x02 \x01(\x08\x32h\n\x0cInternalChat\x12X\n\nStreamChat\x12$.finserve.internal.StreamChatRequest\x1a\".finserve.internal.StreamChatChunk0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STREAMCHATREQUEST']._serialized_start=39
  _globals['_STREAMCHATREQUEST']._serialized_end=134
  _globals['_STREAMCHATCHUNK']._serialized_start=136
  _globals['_STREAMCHATCHUNK']._serialized_end=191
  _globals['_INTERNALCHAT']._serialized_start=193
  _globals['_INTERNALCHAT']._serialized_end=297
# @@protoc_insertion_point(module_scope)
